### PR TITLE
[Major refactoring] Add Service & Validator class, Got rid of throwing exceptions, getters/setters & applied fat domain model

### PR DESCRIPTION
**Pull request by pulkitent**
As a learner/newbie in OOPs & clean code practices, I was exploring and got an eye on this repo and so I thought I should spend my Friday raising a PR by refactoring the codebase as per my knowledge & experience so that I can get some good feedbacks by experienced developers out there :)

-     Update BookingController & its unit test
-     Add BookingService.java & its unit test
-     Add BookingValidator.java & its unit test
-     Update BookingRepository.java
-     Add Restaurant.java model & its unit test
-     Add Booking.java model & its unit test
-     Add  BookingResponseView & its unit test
-     Add basic starter project files

### CODE REVIEW

**Comment by pulkitent** [comment]
@trishagee can you please review it & provide your valuable feedback?

**Comment by trishagee** [comment]
Thank you for this pull request, I'm glad the code was helpful as a project to practice on.

The original status of the code was intentionally as simple as possible for the small amount of code we needed to demo. One part of your refactoring in particular caught my attention, that you moved the classes into separate packages based on architectural function.  This _can_ be useful and is a pattern I have seen frequently in the real world but there are a number of reasons I wouldn't want to use it on this project
1. The project is really too tiny to need splitting into packages at this stage. I would usually wait until it got bigger to work out the best package structure for the application as it evolved
2. I prefer not to separate by architectural function, but instead by business function.  So I would have all restaurant classes (services, models, repositories etc) in the same package. The reason is because I would want to use package/default visibility on the classes and methods that are only needed by restaurant-related functionality to hide those APIs from non-restaurant code. There's an article about this in 97 Things Every Java Programmer Should Know: https://learning.oreilly.com/library/view/97-things-every/9781491952689/ch64.html

Thank you for contributing!

**Comment by pulkitent** [comment]
@trishagee , thank you for your valuable feedback, when I raised this PR in Sep 21 that time I wasn't aware of the way of separation you are suggesting.

But after a few months, I learned about this pattern to bifurcate your classes. Even I feel separating classes by business function also makes the process of extracting a microservice from a monolith very easy (if required in the future)

WDYT?

**Comment by trishagee** [comment]
Yes, in theory separating by business instead of technology level should make it easier to split into business-focused microservices.

**Pull request closed without merging**
